### ISSUE TITLE
Collector uses incorrect version of gets when running bliss init

### ISSUE THREAD

**Issue by dradford** [founderbliss/bliss-cli#2]
Hey there,

When I ran bliss init I received the following error message:

```
Configuring collector...
What's your Bliss API Key?
/usr/local/Cellar/bliss/1.0.41/lib/utils/configuration.rb:51:in `gets': No such file or directory @ rb_sysopen - init (Errno::ENOENT)
```

If you don't precede gets with $stdin it seems that Kernel#gets reads from ARGV as per this SO post.

https://stackoverflow.com/questions/6965885/ruby-readline-fails-if-process-started-with-arguments

I changed line 51 to this locally and it worked:

```
arg = $stdin.gets.chomp
```

**Comment by mikesive** [comment]
Thanks Damien, I've pushed a fix. You can update using homebrew to get the change.
